# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a3b57cd62c62bbd5f137ec9cdbe73acac7bf409c6d38ef6773367d431c97517576ed000ad6b9397d2919b4e6676049cd43d37179070d8787a8f52f8e2436ce2

test:
  secret_key_base: f27709910fc3916aeef21558fc690cdff64ffdf6d8271220b42ce1191254cee45a8c2f65414b70ac1a3d229d71a185475a27c80ecc7536b77f21b097bddfb5d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
